### ISSUE TITLE
show remote host name in command results

### ISSUE THREAD

**Issue by int128** [int128/gradle-ssh-plugin#10]
Currently, console output of command execution does not have its host name. So it is difficult to check which host have occurred error.

**Comment by eendroroy** [comment]
What was the solution?

How can i print the current hostname from my task?

```groovy
task myTask {
    doLast {
        ssh.run {
            session(remotes.prod1, remotes.prod2) {
                println("{{ HOSTNAME, i.e. prod1/prod2 }}")
            }
        }
    }
}
```
