### ISSUE TITLE
sudo with '-u' parameter

### ISSUE THREAD

**Issue by essildoor** [int128/gradle-ssh-plugin#116]
Hi, i've faced with trouble when tried to use executeSudo. Sample code is: executeSudo('-u <some_username> cp <some_filename> <some_dir>'). Script freezes and nothing happens. From ssh client of course I have positive results. Does anybody know something about that? Thank you =)

**Comment by manoj7shekhawat** [comment]
is there any solution to this problem? I can't create a new user.

https://github.com/int128/gradle-ssh-plugin/issues/213
