### ISSUE TITLE
how to change directory of remote server

### ISSUE THREAD

**Issue by mahengyang** [int128/gradle-ssh-plugin#139]
can not use `cd` for remote server

    execute 'cd /tmp'
    println(execute "pwd")

**Comment by int128** [comment]
Execute commands with `&&` as follows:

```groovy
execute 'cd /tmp && pwd'
```

Because `execute` invokes an new shell, the current directory is reset on each time. I am planning to provide the script execution syntax in the future release. Just idea like:

```groovy
executeScript """#!/bin/sh
cd /tmp
pwd
"""
```

**Comment by mahengyang** [comment]
sound good,but I think if these `execute` in session block is actually execute in one shell session will be more usefull

**Comment by int128** [comment]
I found execute accepts commands by multi-line string as like:

```groovy
// multi-line string
execute '''
cd /tmp
pwd
'''

// concat commands
execute [
  'cd /tmp',
  'pwd'
].join('\n')
```
