### ISSUE TITLE
Error during compile referring to number of constructors

### ISSUE THREAD

**Issue by ddykhoff** [int128/gradle-ssh-plugin#141]
I am getting the following error when attempting to run my gradle script. Is this a known issue or is there a solution? 

`Error:(21, 0) Cause: the number of constructors during runtime and compile time for org.hidetake.groovy.ssh.core.settings.OperationSettings$Logging do not match. Expected -1 but got 2`

The relevant bit of code:
`apply plugin: 'org.hidetake.ssh';`

**Comment by int128** [comment]
Gradle 1.x may cause this error. Currently Gradle SSH Plugin requires Gradle 2.0 or later.

**Comment by rbaradari** [comment]
A possible fix in the Groovy SSH dependency would be to extract the Logging enum to a separate file and make it a pure Java implementation. It's not the prettiest thing but then it works for Gradle 1.x too.

**Comment by int128** [comment]
Yup, now I am trying conversion of all enum for Gradle 1.x compatibility on https://github.com/int128/groovy-ssh/pull/43. It looks good but still some tests are failing.

**Comment by ddykhoff** [comment]
Yes I am running Gradle 1.10 when I experience this issue. Unfortunately upgrading to 2.x is not an option in my current environment, so a fix for this would be greatly appreciated! Until then, I will do without it. Thanks for looking into this.

**Comment by int128** [comment]
Released [plugin 1.0.5](https://github.com/int128/gradle-ssh-plugin/releases/tag/v1.0.5) that is compatible with Gradle 1.x. Now I verified all tests are passed on Gradle 1.12. Please let me know if any problem is occurred.
Thanks.

**Comment by ddykhoff** [comment]
Just updated my build to incorporate 1.0.5 and can confirm that it also works with Gradle 1.10! Thanks for your help!
