### ISSUE TITLE
Plugin waits for exit code of jar invoked from within init script, instead of init script exit code

### ISSUE THREAD

**Issue by jblack10101** [int128/gradle-ssh-plugin#144]
In my gradle task, I have something like:
```
executeSudo "/etc/init.d/dropwizard start"
```

And /etc/init.d/dropwizard looks like:
```
#!/bin/bash
case "$1" in
'start')
	cd /opt/dropwizard
	java -jar /opt/dropwizard/dropwizard.jar server /opt/dropwizard/dropwizard-config.yml & echo $! > /opt/dropwizard/dropwizard.pid
        ;;
...
esac
exit 0
```

The gradle script gets hung at the executeSudo above and doesn't return until I kill the dropwizard process on the instance.  So, it seems like the plugin is waiting on the return value of the jar that was started rather than the script that was invoked?  When running 'sudo /etc/init.d/dropwizard start' on the command line, it returns normally and $? will tell me the exit code.

So do you have any suggestions? Or is this a bug?  Thanks!

**Comment by int128** [comment]
`executeSudo` is designed for sudo which needs interaction with password prompt. Does sudo on your environment need a password input? If not, just use `execute 'sudo /etc/init.d/dropwizard start'`.
Thanks.

**Comment by jblack10101** [comment]
I changed it as you suggested, but it is still waiting on the exit code from the dropwizard jar rather than the init script.

**Comment by int128** [comment]
Got it! Would you try following init script?

```sh
#!/bin/bash
case "$1" in
'start')
    cd /opt/dropwizard
    nohup java -jar /opt/dropwizard/dropwizard.jar server /opt/dropwizard/dropwizard-config.yml < /dev/null > /dev/null 2> /dev/null & echo $! > /opt/dropwizard/dropwizard.pid
        ;;
...
esac
exit 0
```

Since the ssh client waits until both input and output stream return EOF, we have to redirect those to /dev/null as above. We can verify this behavior by these commands:

```sh
# this waits 10 sec
ssh localhost '/bin/sleep 10 &'

# this waits 10 sec (nohup prevent from killing by signal HUP)
ssh localhost 'nohup /bin/sleep 10 &'

# immediately exits
ssh localhost 'nohup sleep 10 < /dev/null > /dev/null 2> /dev/null &'
```

**Comment by jblack10101** [comment]
Awesome, it works. Thanks so much!
