### ISSUE TITLE
JSCH can't read from /etc/ssh/ssh_known_hosts

### ISSUE THREAD

**Issue by dkowis** [int128/gradle-ssh-plugin#151]
I know this is not a gradle-ssh-plugin problem, but I'm going to file this here, because here's where the symptoms show up, and it took me quite a while to trace down the root cause.

http://sourceforge.net/p/jsch/bugs/61/ This bug has been open in JSCH for a very, very long time. 

Puppet can manage SSH host keys for `known_hosts`, but only for the `/etc/ssh/ssh_known_hosts` file: https://docs.puppetlabs.com/references/latest/type.html#sshkey

The combination of these two things makes it rather difficult to use JSCH when you deploy your jenkins slaves via puppet and you want to avoid manual steps, like adding an SSH host key to the user's `known_hosts` file.

**Comment by int128** [comment]
Thanks for the issue.
JSch provides `HostKeyRepository` and maybe it is possible to set 2 or more `known_hosts` file. Currently the plugin provides the `knownHosts` property as a File but it should be able to also set a list of files. I will implement it in the future release.

**Comment by int128** [comment]
`knownHosts` accepts one or more files since 2.3.0.
