### ISSUE TITLE
How to set keepAlive ?

### ISSUE THREAD

**Issue by jzillmann** [int128/gradle-ssh-plugin#152]
I'm having problems with long running commands sometimes freeze from time to time (on target host the command finishes but the client is stuck showing an not up-to-date output.

Now i wanted to try if jsch keep alive (http://www.mail-archive.com/jsch-users@lists.sourceforge.net/msg00659.html) does make any difference.

Is there some option to enable this ?

**Comment by int128** [comment]
Unfortunately no option is available at this moment. I will add keep-alive option (enable by default) in the next release.
Thanks.

**Comment by int128** [comment]
SSH keep-alive setting is added in v1.1.7. Interval of keep-alive packets is 60 seconds by default. Please try the new release.
