### ISSUE TITLE
User guide makes incorrect reference to knownHosts key

### ISSUE THREAD

**Issue by kenocrates** [int128/gradle-ssh-plugin#155]
Example in section 2.1.2 on page https://gradle-ssh-plugin.github.io/user-guide.html
EXPECT: knownHosts = allowAnyHosts
ACTUAL: knownHost = allowAnyHosts

Also, I believe this key should be included in the gateway examples here:

https://github.com/int128/gradle-ssh-plugin/wiki/Access-through-gateways

**Comment by int128** [comment]
Fixed user guide and added gateway examples:
https://github.com/gradle-ssh-plugin/gradle-ssh-plugin.github.io/pull/10
https://github.com/gradle-ssh-plugin/gradle-ssh-plugin.github.io/pull/11

Thank you.
