### ISSUE TITLE
Known_hosts dosn't work

### ISSUE THREAD

**Issue by kulik** [int128/gradle-ssh-plugin#157]
Connection rejected http://screencloud.net/v/3NP0

but it is work good with allowAnyHosts

http://screencloud.net/v/lDkR

**Comment by int128** [comment]
Please verify `known_host` by `ssh-keygen` command as follows:

```sh
ssh-keygen -F 10.8.0.20 -f '../deploy/known_hosts'
```

What kind of key does `known_hosts` contain? Currently it supports only RSA or DSA host key but not ECDSA key.

**Comment by kulik** [comment]
Thank you. Yes. It is contains ECDSA key. so i should recreate it on host

**Comment by int128** [comment]
Sorry for inconvenience. It will be supported in the near future.
Thank you.
