### ISSUE TITLE
Solution to start background processes and keep them alive after Gradle script ends

### ISSUE THREAD

**Issue by superjames** [int128/gradle-ssh-plugin#158]
What is the solution to run multiples remote scripts that don't stop when finishing the gradle script execution ?

I've tried things like :

    executeBackground 'nohup start_my_web_server.sh &'
    executeBackground 'nohup start_my_database_server.sh &'

but processes stop when stopping the Gradle script.

Thanks

**Comment by int128** [comment]
Please try `nohup start_my_web_server.sh < /dev/null > /dev/null 2> /dev/null &`.
See #144.

**Comment by superjames** [comment]
Thanks

This worked for me :
            executeBackground "nohup sh -c '( ( ${cmd} ) & )'"
