### ISSUE TITLE
can not read /etc/profile?

### ISSUE THREAD

**Issue by mahengyang** [int128/gradle-ssh-plugin#159]
I set my maven home in /etc/profile as

    export MAVEN_HOME=/usr/local/mvn
    export PATH=$PATH:$MAVEN_HOME/bin

It seems gradle-ssh-plugin did not read this file,I haven to set absolute path for maven in my build.gradle file

    task xxx(dependsOn: getRemoteServer) << {
        ssh.run {
            session(remoteServer) {
                println(execute "/usr/local/mvn/bin/mvn clean install")
            }
        }
    }

any suggest?

**Comment by int128** [comment]
The shell (bash, zsh, etc.) on the remote server does not read /etc/profile. It depends on the server settings but not gradle-ssh-plugin.

See also http://stackoverflow.com/questions/216202/why-does-an-ssh-remote-command-get-fewer-environment-variables-then-when-run-man

**Comment by mahengyang** [comment]
ths,perfect answer
