### ISSUE TITLE
Logging level not working

### ISSUE THREAD

**Issue by mrniko** [int128/gradle-ssh-plugin#161]
With latest version of plugin logging level setting stop to work. Gradle 2.4, plugin version 1.1.3
```groovy
task deploy << {
   ssh.run {
      // not works anymore
      logging.level = LogLevel.INFO
   }
}
```

**Comment by int128** [comment]
Sorry for the late reply.
Logging setting has been removed since v0.4.0.
https://gradle-ssh-plugin.github.io/docs/#_logging_settings

```groovy
ssh.settings {
  logging = 'stdout'
}
```
