### ISSUE TITLE
Allow Include/Exclude patterns with put/get commands

### ISSUE THREAD

**Issue by johnjaylward** [int128/gradle-ssh-plugin#168]
```groovy
 put ( fileTree(dir:"$coreDir/src/main/sql/",excludes: [
                '**/archives/**'
            ]), "destDir/" )
```

Will put all the files flat in "destDir" with no sub directories even though the tree defines them

``` groovy
file("$coreDir/src/main/sql/").listFiles().findAll {!it.name.equals("archive")}.collect {
    put it, "destDir/"
}
```

Will put all the files in the proper place, but then I'm calling put quite possibly many more times than I need to.

it would be nice to have the put/get methods accept a CopySpec to reduce scripting on the user side.

**Comment by int128** [comment]
Thanks for your idea. File filter is available in 2.4.0. `fileTree` is not supported yet due to technical difficulty but file filter feature may cover almost needs.
