### ISSUE TITLE
Connection retry fails with Packet corrupt

### ISSUE THREAD

**Issue by leslie-leder** [int128/gradle-ssh-plugin#172]
When configuring the connection settings like so:
    remotes {
      vboxguest{
       ...
        retryCount = 10
        retryWaitSec = 3
      }
   }

I get always the following console output: 
    Retrying: com.jcraft.jsch.JSchException: Session.connect: java.net.SocketException: Connection reset
    Retrying: com.jcraft.jsch.JSchException: Auth fail
    Retrying: com.jcraft.jsch.JSchException: Packet corrupt
    Retrying: com.jcraft.jsch.JSchException: Packet corrupt
    Retrying: com.jcraft.jsch.JSchException: Packet corrupt
    Retrying: com.jcraft.jsch.JSchException: Packet corrupt

When placing the ssh run code into while loop with same parameters it reliably succeeds. 
    ssh.run {
        session(remotes.vboxguest) {
          //do some copy
        }
     }

Is there some repetition problem known?

**Comment by int128** [comment]
I hope this helps, please see https://github.com/int128/gradle-ssh-plugin/issues/133#issuecomment-67487121

**Comment by leslie-leder** [comment]
The referred issue is complaining about **message too long error** and is also linking to [this article](http://www.snailbook.com/faq/sftp-corruption.auto.html). 

I would rather guess [this article](http://flyingjxswithjava.blogspot.de/2015/03/comjcraftjschjschexception-packet.html) may describe the reason.

Yes the shell does output some text. But I can connect with Groovy SSH properly if the sshd is up and running.
I use the gradle-ssh-plugin in order to configure a virtualbox vm via ssh. After starting the vm the linux inside needs some time to get running.  
In order to avoid a fixed waiting time I use ssh connection polling to find out if the machine is up. 

If I do so by my own loop (ugly) it perfectly works. I creates a session per loop.

If I do so with retryCount, ... (nice) it fails with packet corrupt error. I don't know how many underling sessions are created.
--leslie

**Comment by Odinodin** [comment]
We're seeing the same problem when we use the Groovy SSH plugin directly. It happened after upgrading from 1.1.5 to 1.1.7..

**Comment by leslie-leder** [comment]
I've checked gradle-ssh-plugin version 1.1.4. The problem is the same whereas it prints a different error message. 
With version 1.1.4 it still works with my explicit retry loop. But when using **retryCount**

*Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.
Retrying: com.jcraft.jsch.JSchException: Auth fail
Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.
Retrying: com.jcraft.jsch.JSchException: Auth fail
...*
 
--leslie

**Comment by leslie-leder** [comment]
Sorry. This was my fault. 
It work with 1.1.4.
Thanks
--Leslie

**Comment by int128** [comment]
Thank you for checking the new version.
