### ISSUE TITLE
SFTP mkdir support

### ISSUE THREAD

**Issue by Silnar** [int128/gradle-ssh-plugin#173]
Hi

Is it possible to invoke sftp mkdir command using gradle-ssh plugin ?

I managed to send a file to an sftp server, but it works only when target directory exists.

Cheers.

**Comment by int128** [comment]
Please add `execute "mkdir /xxx/xxx"` before file transfers.

The plugin has `sftp` syntax (experimental and not yet documented) but `mkdir` of sftp would fail if the directory already exists due to sftp specification.

```groovy
// experimental
            session(ssh.remotes.testServer) {
                sftp {
                    mkdir folder.path
                }
            }
```

Thanks.

**Comment by Silnar** [comment]
Hmm... interesting :)
I'll try it.
Thanks.

**Comment by Silnar** [comment]
`execute "mkdir /xxx/xxx"` didn't work. It made gradle hang forever.

Experimental session.sftp worked ok and for now I solved creating subdirs this way:
```
session(ssh.remotes.testServer) {
  sftp {
    mkdir 'dir'
    mkdir 'dir/subdir'
  }
  put from: jar.archivePath, into: '/dir/subdir'
}
```
If there is a better way, please let me know.

Thanks.

**Comment by cleankod** [comment]
Did you find a solution for the already existing directory maybe? I mean I would like to create a directory only if it does not exist or ignore the error on `mkdir` saying that the directory already exists.

**Comment by int128** [comment]
Just execute `mkdir -p xxx` to silently ignore an already existing directory.

**Comment by cleankod** [comment]
sftp does not accept `-p` parameter.

**Comment by int128** [comment]
`mkdir` of sftp fails if the directory already exists due to the sftp specification. So please execute `mkdir` command as follows.

```groovy
execute 'mkdir -p xxx'
```
