### ISSUE TITLE
remove() fails if the file/dir does not exist

### ISSUE THREAD

**Issue by mvysny** [int128/gradle-ssh-plugin#206]
I found out that the remove() method fails if the directory does not exist:

> Caused by: org.hidetake.groovy.ssh.operation.SftpException: Failed SFTP STAT: docserver:/docs/lsps/doc_root/Stage3_2: (SSH_FX_NO_SUCH_FILE: A reference was made to a file which does not exist): No such file
	at org.hidetake.groovy.ssh.operation.SftpOperations.stat(SftpOperations.groovy:187)
	at org.hidetake.groovy.ssh.extension.SftpRemove$Trait$Helper$_remove_closure1$_closure2.doCall(SftpRemove.groovy:18)
	at org.hidetake.groovy.ssh.extension.SftpRemove$Trait$Helper$_remove_closure1.doCall(SftpRemove.groovy:17)
	at org.hidetake.groovy.ssh.extension.SftpRemove$Trait$Helper$_remove_closure1.doCall(SftpRemove.groovy)
Caused by: 2: No such file
	at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2846)
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2198)
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:2215)
	at com.jcraft.jsch.ChannelSftp.stat(ChannelSftp.java:2172)
	at com.jcraft.jsch.ChannelSftp$stat.call(Unknown Source)
	at org.hidetake.groovy.ssh.operation.SftpOperations.stat(SftpOperations.groovy:182)
	... 91 more

You can employ the `exists()` function I wrote earlier to check whether the file exists, at `SftpRemove.groovy:18`. Thanks! :)

**Comment by mvysny** [comment]
Workaround is to define the `exists()` function:
>    boolean exists(String dir, Object sftp) {
        try {
            sftp.channel.stat(dir)
            return true
        } catch (Exception ex) {
            if (ex.class.getName() == 'com.jcraft.jsch.SftpException' && ex.id == 2) {
                // file not found
                return false
            }
            throw ex
        }
    }

And call it properly:

                sftp {
                    println "Deleting $dir"
                    if (exists(dir, delegate)) {
                        remove dir
                    }
                }

**Comment by int128** [comment]
I thought it is natural that `remove` throws error if removing target is not found but I found popular methods such as Gradle `project.delete()` or Java `File.delete()` return boolean as result. So I will change return type of `remove()` to boolean and not to throw error even if target is not existed. How do you think?
Thanks.

**Comment by centic9** [comment]
Please note that providing the boolean return value of `File.delete()` instead of an IOException is seen as a mistake by many developers. An Exception would be more appropriate for many of the errors that can happen in the delete(). 

All too often the delete-return is not checked, thus static checkers like FindBugs, Sonar, Checkstyle all have warnings for instances where this delete() is not done.

**Comment by mvysny** [comment]
Thank you for your response. I also think `File.delete()` returning boolean is a huge design flaw - please don't do that :-) Gradle's `project.delete()` AFAIK does nothing if the directory does not exist - this result of the directory not present in the filesystem is the desired result of the operation after all. So I would very much like the following behavior, identical to Gradle's `project.delete()`:

1. If the directory or file does not exist, return `false`
2. If the directory or file does exist, delete it. If the directory or any subdir fails to be deleted, throw IOException. If the operation succeeds, return `true`

This way, the outcome of the `remove()` operation can be safely ignored, yet you will be informed with an exception on a failure.

If this is not acceptable, please at least consider adding the exists() function - I have read somewhere that if a function A throws an exception, there should be another function B which checks whether A will fail, so that you can avoid catching exceptions and parsing away messages from them.

**Comment by int128** [comment]
Thank you for advices. In most deployment scenario, `remove()` should do nothing if the directory does not exist for removing possible existing directory. Also it should throw an exception for checking the error cause unlike in the case of `File.delete()`.

I think the behavior you suggest is the best. `remove(paths...)` takes one or more paths, so following behavior seems good:

1. If one or more paths do not exist, delete only existing paths and return `false`.
2. If all paths exist, delete them and return `true`.
3. If any directory or file fails to be deleted, throw `SftpException`.

**Comment by mvysny** [comment]
I agree with the spec you are suggesting, sounds good. Thank you.

**Comment by int128** [comment]
Fixed in 1.5.1.
