### ISSUE TITLE
How to force scp rather than sftp

### ISSUE THREAD

**Issue by phoenixnebula** [int128/gradle-ssh-plugin#220]
May be my question is dumb and I am just using this for firsttime i read the document twice for setting the fileTransferMethod as scp , the document doesnot speak about it.

document link:
https://gradle-ssh-plugin.github.io/docs/

I tried to put 
fileTransferMethod =scp
fileTransferMethod ='scp'
fileTransferMethod :scp

at remote revel and tried but all times it failed , and even if it worked it only worked as sftp defaulted
Can any one please help?

**Comment by sethamclean** [comment]
I'm having the same issue. The documentation is not clear on where this value should be set and attempting to set it as part of the ssh.settings results in ``` > No such property: fileTransferMethod for class: org.hidetake.groovy.ssh.core.settings.CompositeSettings ```

**Comment by int128** [comment]
Sorry, the document was wrong. Please put `fileTransfer = 'scp'`.

**Comment by int128** [comment]
Fixed in https://github.com/int128/groovy-ssh/commit/a2a1ac6699d5f747e25f1be4386fbfab28ffa80c.

**Comment by sethamclean** [comment]
This doesn't seem to work either:

```> No such property: fileTransfer for class: org.hidetake.groovy.ssh.core.settings.CompositeSettings```

**Comment by int128** [comment]
Using 2.2.0 or later? SCP support is available since 2.2.0. See also #226, acceptance tests of `fileTransfer` are passed with the latest version.

**Comment by sethamclean** [comment]
@int128 Sorry I was using this as a reference per the README.md
https://github.com/int128/gradle-ssh-plugin/releases
The latest appeared to be 2.1.0 at the time I was setting this up. The latest according to this page now is 2.1.2.

**Comment by sethamclean** [comment]
I pulled the repo and looked for a 2.2.0 tag. The latest I see is 2.1.2. groovy-ssh also seems to only have tags up to 2.1.2.

**Comment by int128** [comment]
@sethamclean Sorry, I mistook, the latest is 2.1.2 as you said. Would you try `gradlew buildEnvironment`?

**Comment by sethamclean** [comment]
+--- org.hidetake:gradle-ssh-plugin:1.1.3
|    \--- org.hidetake:groovy-ssh:1.1.7
|         +--- org.slf4j:slf4j-api:1.7.7
|         +--- com.jcraft:jsch:0.1.52
|         +--- com.jcraft:jsch.agentproxy.connector-factory:0.0.7
|         |    +--- com.jcraft:jsch.agentproxy.core:0.0.7
|         |    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.7
|         |    |    +--- com.jcraft:jsch.agentproxy.core:0.0.7
|         |    |    +--- net.java.dev.jna:jna:3.4.0
|         |    |    \--- net.java.dev.jna:platform:3.4.0
|         |    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.7
|         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.7
|         |    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.7
|         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.7
|         |    \--- com.jcraft:jsch.agentproxy.pageant:0.0.7
|         |         +--- com.jcraft:jsch.agentproxy.core:0.0.7
|         |         +--- net.java.dev.jna:jna:3.4.0
|         |         \--- net.java.dev.jna:platform:3.4.0
|         \--- com.jcraft:jsch.agentproxy.jsch:0.0.7
|              +--- com.jcraft:jsch:0.1.49 -> 0.1.52
|              \--- com.jcraft:jsch.agentproxy.core:0.0.7
\--- com.gradle:build-receipt-plugin:1.0

**Comment by int128** [comment]
Hmm... How about cleaning the cache in .gradle?

**Comment by sethamclean** [comment]
It turns out a parent project was using an older version of your plugin. Sorry for all the hassle and thanks for the great plugin.

**Comment by Success-Guy** [comment]
The documentation [Here](https://www.jenkins.io/doc/pipeline/steps/ssh-steps/) does not even have **fileTransfer** map key to the remote credential Map variable.
It took me almost a day before finding out the solution.
How do I update the documentation on Jenkins.io. I'd like to solve this for others too.
