### ISSUE TITLE
[question] how to run a background process and exit 

### ISSUE THREAD

**Issue by foxundermoon** [int128/gradle-ssh-plugin#231]
i'm try to start a process by ssh.run,but it always suspend.
`java -jar  xxx.jar &`
`java -jar  xxx.jar & exit 0`
`nohup java -jar  xxx.jar`
`nohup java -jar  xxx.jar &`
`java -jar  xxx.jar 1>dev/null 2>dev/null`
`java -jar  xxx.jar  >dev/null  2>&1`
`... and so on`
t.m tried both  `execute` and `executeBackground`
i was try every method,but can not exit, always suspend

**Comment by int128** [comment]
Maybe standard input of the process is connected to SSH channel, so try following:

```sh
nohup java -jar xxx.jar < /dev/null > /dev/null 2> /dev/null &
```

See also #144.
