### ISSUE TITLE
apply plugin: 'org.hidetake.ssh' throws java.lang.NoClassDefFoundError: org/hidetake/groovy/ssh/Ssh

### ISSUE THREAD

**Issue by dragan-sassler** [int128/gradle-ssh-plugin#232]
I have a project with gradle-ssh-plugin which works fine when the computer is connected to the internet. I installed the same project on an computer without internet connection. All necessary libraries are in directory "libs".
`apply plugin: 'org.hidetake.ssh'` in build.gradle throws following exception:
java.lang.NoClassDefFoundError: org/hidetake/groovy/ssh/Ssh
Libraries: gradle-ssh-plugin-2.2.0.jar, groovy-ssh-2.2.0.jar, jsch-0.1.52.jar and jsch.agentproxy...0.0.7.jar are in "libs" directory
My environment is:
Gradle 2.8
Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.6.0_45 (Sun Microsystems Inc. 20.45-b01)
OS:           Windows Server 2008 R2 6.1 x86

**Comment by int128** [comment]
Would you try to load lbs in `buildscript` block as follows?

```groovy
buildscript {
  dependencies {
    classpath fileTree(dir: 'libs', include: '*.jar')
  }
}
apply plugin: "org.hidetake.ssh"
```

See also:
https://docs.gradle.org/current/userguide/organizing_build_logic.html#sec:external_dependencies
https://docs.gradle.org/current/userguide/dependency_management.html#sub:file_dependencies

**Comment by dragan-sassler** [comment]
It works. Thanks!
My configuration was wrong:
```
buildscript {
	repositories {
			flatDir {
				dirs "$projectDir/libs"
			}
	}
	dependencies {
		classpath "org.hidetake:gradle-ssh-plugin:2.2.0"
	}
}

apply plugin: 'org.hidetake.ssh'

```
