### ISSUE TITLE
[question]  how to open another shell session from opened shell session

### ISSUE THREAD

**Issue by foxundermoon** [int128/gradle-ssh-plugin#241]
hostA(me) -> hostB->hostC
consider security ，hostA can not connect hostC.so i need  jump over hostB. use ssh command is easy but i don't know how to use the gradle-ssh. can you help me & give me one solution.

**Comment by foxundermoon** [comment]
I found the way, to use gateway setting.

**Comment by int128** [comment]
Exactly. See https://gradle-ssh-plugin.github.io/docs/#_connect_through_gateway_servers for details.
