### ISSUE TITLE
doFirst / doLast Support

### ISSUE THREAD

**Issue by noelob** [int128/gradle-ssh-plugin#246]
In order to do integration testing I need to set up a tunnel to a remote database, and I can achieve this using forwardLocalPost. From what I can tell, the tunnel is only open for the scope of the session {} closure.
 
However, I want to incorporate this into my integration test task (which is of type Test) and cannot find a way to make the two work together. My task would ideally looks like this:

```
task integrationTest(type: Test) {
  testClassesDir = sourceSets.integrationTest.output.classesDir
  classpath = sourceSets.integrationTest.runtimeClasspath
  outputs.upToDateWhen { false }

  doFirst {
    // set up tunnel
  }

  doLast {
    // teardown tunnel
  }
}
```
Is there a way to achieve this with this Gradle plugin?

Thanks,
Noel

**Comment by int128** [comment]
We can keep a tunnel in a background thread as follows:

```groovy
task integrationTest(type: Test) {
  testClassesDir = sourceSets.integrationTest.output.classesDir
  classpath = sourceSets.integrationTest.runtimeClasspath
  outputs.upToDateWhen { false }

  doFirst {
    // set up tunnel
    ext.ready = new java.util.concurrent.CountDownLatch(1)
    ext.done = new java.util.concurrent.CountDownLatch(1)
    Thread.start {
      ssh.run {
        session(...) {
          forwardLocalPort port: 5432, hostPort: 5432
          ready.countDown()
          done.await()
        }
      }
    }
    ready.await()
  }

  doLast {
    // teardown tunnel
    done.countDown()
  }
}
```

The plugin does not provide async methods currently but will do in the future release.

**Comment by noelob** [comment]
This works great, thanks!
