### ISSUE TITLE
Support execution of local shell scripts

### ISSUE THREAD

**Issue by matthiasbalke** [int128/gradle-ssh-plugin#249]
The `execute` method has support for outputStream and errorStream. It would be great to have support for inputStream too. This way one could execute local shell scripts remotly without transfering them as a file first.

An `exceute(<path to local script>)` method could be provided to support a basic use case.
While access to standardInput would be provided for advanced use cases.

**Comment by int128** [comment]
Added this feature in the release 2.6.0. Thank you for the proposal.
