### ISSUE TITLE
remove doesnt work recursively?

### ISSUE THREAD

**Issue by Sorreldd** [int128/gradle-ssh-plugin#253]
Hi,
I used org.hidetake.ssh version '2.4.0'
if i try remove folder with folders and files, remove does not work recursively,
but in org.hidetake.ssh version '2.3.0' all ok

Thanks,
Artyom

**Comment by int128** [comment]
Tests passed on 2.4.0 as #254. Would you tell me your environment e.g. OS, JVM and Gradle version?

**Comment by Sorreldd** [comment]
Gradle version 2.10
OS professional Windows 8.1
Server running on VirtualBox Debian(x64) 8.2 (jessie)
java version 1.8.0_92

my task
task uninstallServerJcp << {
    ssh.run {
        session(remotes.cpServer) {
            remove "$serverHome/JCP"
        }
    }
}
uninstallServerJcp.onlyIf { ant.properties['injcp'] }


> gradle uninstallServerJcp -Dinjcp=1

:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Build setup for BV
:fp.web.env:uninstallServerJcp
Host key checking is off. It may be vulnerable to man-in-the-middle attacks.
:fp.web.env:uninstallServerJcp FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\komarov\git\chequepay\fp.web.env\build.gradle' line: 673

* What went wrong:
Execution failed for task ':fp.web.env:uninstallServerJcp'.
> No signature of method: org.hidetake.groovy.ssh.session.transfer.SftpRemove$Trait$Helper$_remove_closure1$_closure2$_closure4.call() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [/home/master/fp_server/JCP/lib/extra]
Possible solutions: any(), any(), any(groovy.lang.Closure), each(groovy.lang.Closure), any(groovy.lang.Closure), each(groovy.lang.Closure)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
on version 'org.hidetake.ssh' version '2.3.0' all ok and build success

**Comment by Sorreldd** [comment]
![image](https://cloud.githubusercontent.com/assets/2545203/17168620/11e54bb8-53ec-11e6-97eb-8edbc4f71a5f.png)

**Comment by int128** [comment]
Thanks for details. I could reproduce this bug on Java 8. It will be fixed in 2.4.1.

**Comment by int128** [comment]
>Caused by: groovy.lang.MissingMethodException: No signature of method: org.hidetake.groovy.ssh.session.transfer.SftpRemove$Trait$Helper$_remove_closure1$_closure2$_closure4.call() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [/tmp/hoge/foo/bar]
Possible solutions: any(), any(), any(groovy.lang.Closure), each(groovy.lang.Closure), any(groovy.lang.Closure), each(groovy.lang.Closure)
	at org.hidetake.groovy.ssh.session.transfer.SftpRemove$Trait$Helper$_remove_closure1$_closure2$_closure4$_closure5.doCall([SftpRemove.groovy:54](https://github.com/int128/groovy-ssh/blob/2.4.0/core/src/main/groovy/org/hidetake/groovy/ssh/session/transfer/SftpRemove.groovy#L54))

**Comment by int128** [comment]
Fixed in 2.4.1.
