### ISSUE TITLE
Unable to pass ssh key identity as a System variable to gradle ssh plugin 2.4

### ISSUE THREAD

**Issue by oldbonez** [int128/gradle-ssh-plugin#255]
Hello, 
I'm using gradle 2.13 and gradle ssh plugin 2.4 to develop a custom class for executing things from SSH on remote machine. This is something similar to issue #183. 
 Here is my code
`    
package com.foo.gradle.executor

     import org.gradle.api.Project
     import org.gradle.api.GradleException
     import org.hidetake.groovy.ssh.Ssh

         class SshExecutor implements ConfigurableExecutor {
         String name = "ssh"
          int priority = 1
          Project project
    
    @Override
    void execute(Command command, Os os) {
	
		println "Opening an SSH connection. Cross your fingers!"
    
		def sshConnection = Ssh.newService()
    
		println "Connection opened"

		println sshConnection

		sshConnection.settings {
			knownHosts = allowAnyHosts
			agent = false
	    }
		
		sshConnection.remotes { 
		   buildHost {
		      role 'buildtarget'
              host = 'foo'
			  user = System.getenv()["USERNAME"]
			  identity = System.getenv()["BULD_SSH_KEY"]
		      }
		}
		
		sshConnection.run { 
		      session(sshConnection.remotes.buildHost) {
		      def result = execute 'uname -a'
			  println "execution test" + result
		      }
		}
   }
    void configure(ExecutorConfiguration config, Project project) {
        this.project = project
    }
	

   @Override
    boolean match(Os os) {
        return os.getName() == "SunOS_5.10"
    }
}
`

When running this code through gradle build I get the error

` com.jcraft.jsch.JSchException: invalid privatekey: [B@444a30a7`

In debug mode I have the following SSH snippet

`13:50:47.478 [QUIET] [system.out] Opening an SSH connection. Cross your fingers!
13:50:47.794 [QUIET] [system.out] Connection opened
13:50:47.794 [QUIET] [system.out] org.hidetake.groovy.ssh.core.Service@76f725f5
13:50:47.861 [DEBUG] [org.hidetake.groovy.ssh.session.Executor] Using default settings: {fileTransfer=sftp, jschLog=false, retryWaitSec=0, pty=false, authentications=[publickey, keyboard-interactive, password], agentForwarding=false, keepAliveSec=60, sudoPath=sudo, dryRun=false, encoding=UTF-8, retryCount=0, logging=slf4j, knownHosts=/home/foo/.ssh/known_hosts, ignoreError=false, agent=false}
13:50:47.866 [DEBUG] [org.hidetake.groovy.ssh.session.Executor] Using global settings: {}
13:50:47.869 [DEBUG] [org.hidetake.groovy.ssh.session.Executor] Using per-service settings: {}
13:50:47.946 [DEBUG] [org.hidetake.groovy.ssh.session.Executor] Using per-remote settings: {user=BB, identity=...}
13:50:48.002 [DEBUG] [org.hidetake.groovy.ssh.connection.ConnectionManager] Connecting to buildHost [fooo:22] with {keepAliveSec=60, retryCount=0, retryWaitSec=0, knownHosts=allowAnyHosts, agent=false, identity=..., authentications=[publickey, keyboard-interactive, password], user=foo}`

The private key in OpenSSH format
`-----BEGIN RSA PRIVATE KEY-----
------END RSA PRIVATE KEY-------`

However, if I enable the SSH agent, I'm connecting. Can you help me with a sample code to understand what method I should use to specify the SSH KEY as variable?
Many thanks!

**Comment by int128** [comment]
The plugin treats value of `identity` setting as a key content, not a key path. Try to fix the script as follows:

```
          identity = new File(System.getenv('BULD_SSH_KEY'))
```

**Comment by oldbonez** [comment]
Many thanks! It's working. Would you please include this example in the documentation?

**Comment by int128** [comment]
Okay. I will fix the docs.
