### ISSUE TITLE
Gradle 3.2 deprecation of task myTask() << {...}

### ISSUE THREAD

**Issue by leon** [int128/gradle-ssh-plugin#282]
In gradle 3.2 they have deprecated the left shift operator of the task interface.
https://docs.gradle.org/current/release-notes#deprecations

```
// WRONG: Description assigned in execution phase
task helloWorld << {
    description = 'Prints out a message.'
    println 'Hello world!'
}

// CORRECT: Description assigned in configuration phase
task helloWorld {
    description = 'Prints out a message.'
    doLast {
        println 'Hello world!'
    }
}
```

Should I simply do the same and wrap `ssh.run` with `doLast` or is there a cleaner way?

**Comment by NielsUll** [comment]
Yes, please wrap in doLast instead.
It will avoid warnings during build when using the plugin.
By the way, note that the two code samples are NOT identical - the description will be set at different times!

**Comment by rm--** [comment]
@leon The link points not to the correct page.
Check this one: https://docs.gradle.org/3.2/release-notes#deprecations.
