### ISSUE TITLE
Version 2.10 not runnable on java 8

### ISSUE THREAD

**Issue by stipx** [int128/gradle-ssh-plugin#328]
Although it states that release 2.10 is built with java 11 but still runnable with java 8 it is not.

> java.lang.UnsupportedClassVersionError: org/hidetake/gradle/ssh/plugin/SshPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Ghazghkull** [comment]
This also happens to me :(

**Comment by int128** [comment]
The compiler option seems not work. I will try other options.

**Comment by int128** [comment]
Version 2.10.1 should fix this.
