### ISSUE TITLE
Host key verification failed for ECDSA host key

### ISSUE THREAD

**Issue by int128** [int128/gradle-ssh-plugin#55]
It seems JSch does not support ECDSA key in known_hosts file.
I found this in checking acceptance test, because host key is ECDSA in Travis CI.

**Comment by ymnk** [comment]
The latest jsch version has supported ECDSA host keys.
    http://search.maven.org/#artifactdetails%7Ccom.jcraft%7Cjsch%7C0.1.52%7Cjar
It may be worth trying.

**Comment by int128** [comment]
Thank you for the announce of new release.
I tried the latest version (0.1.52) and tests for _user_ key is passed but tests for _host_ key is failed.
Please let me know any hint.
Here is the pull request including these tests: https://github.com/int128/groovy-ssh/pull/59
Thanks.

**Comment by jggc** [comment]
@int128 Is there a way to work around this issue by doing something like they do in the Ant jsch plugin to skip host key verification? This prevents my organization from updating to a recent openssh server version.

http://www.techcrony.info/2013/03/24/nitingautam/jschexception-reject-hostkey/

**Comment by jggc** [comment]
Okay I just found this

**Comment by mvysny** [comment]
Alternative is to ssh via RSA:
1. ssh -o FingerprintHash=md5 -o HostKeyAlgorithms=ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-dss-cert-v00@openssh.com,ssh-rsa,ssh-dss user@server
2. remove the offending key from ~/.ssh/known_hosts
3. ssh again
4. copy the new known_hosts with the RSA host key somewhere, e.g. to your git repo
5. in your gradle file, reference this known_hosts file:
ssh.settings {
    knownHosts = file('known_hosts')
}
