### ISSUE TITLE
defines a session for multiple remote roles

### ISSUE THREAD

**Issue by int128** [int128/gradle-ssh-plugin#8]
currently function `remotes.role()` takes only 1 role, so should accept more arguments:

``` groovy
sshexec {
  session(remotes.role('dbservers', 'appservers')) {
    execute '...'
  }
}
```

**Comment by JoaoFlach** [comment]
it could accept an array of String also. It would be more dynamic.
`
def servers = {'dbservers', 'appservers'}
session(remotes.role(servers)) {
    execute '...'
}
`
