### ISSUE TITLE
No put method?

### ISSUE THREAD

**Issue by mauromol** [int128/gradle-ssh-plugin#90]
After setting up my build script, if I declare and run:

``` groovy
task deployTest2(type: SshTask, dependsOn: war) {
    session(remotes.testServer) {
        put(war.archivePath, "$deployTestDir/myfile.war")
    }
}
```

I receive the following error:

```
No signature of method:
org.hidetake.gradle.ssh.internal.session.DefaultSessionHandler.put() is applicable for argument types:
(java.io.File, org.codehaus.groovy.runtime.GStringImpl) values: [C:\path/to/myWar.war, ...]
```

From a quick look at the plugin source code, I can't find any mention of put and get methods in SessionHandler... What am I doing wrong?

**Comment by percula** [comment]
I'm getting this error, but I think it's because I'm on Gradle 6+. It was working just fine when I was on Gradle 5.6. Can you please release a version that is compatible with Gradle 6+? I noticed the commits are there, just a release is needed. Thanks!
